### ISSUE TITLE
Catchplay doesn't work (I think there's a problem with the header)

### ISSUE THREAD

**Issue by shinnosukee** [wayneclub/Subtitle-Downloader#15]
Today I trying to rip the subtitle on Catchplay, but it doesn't work when parsing the mpd manifest.

![image](https://user-images.githubusercontent.com/55194978/155262516-48cb655b-ca71-4a91-a116-e26a7691d2f5.png)

**Comment by wayneclub** [comment]
Use debug mode and upload the complete log. The Indonesian API may be different than Taiwan's API.
