### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by viva9grup** [wayneclub/Subtitle-Downloader#18]
hello,
Please advice, i always got Timeout, please retry

Sekuat Cahaya Mentari

Season 1 total: 18 episode(s)   update to episode 19    download all episodes
---------------------------------------------------------------
Chromedriver is already installed.
Finding Sekuat Cahaya Mentari.S01E01.WEB-DL.WeTV.vtt ...

Timeout, please retry.

**Comment by wayneclub** [comment]
> hello, Please advice, i always got Timeout, please retry
> 
> Sekuat Cahaya Mentari
> 
> ## Season 1 total: 18 episode(s) update to episode 19 download all episodes
> Chromedriver is already installed. Finding Sekuat Cahaya Mentari.S01E01.WEB-DL.WeTV.vtt ...
> 
> Timeout, please retry.

Fixed, please re-download the project and follow the instruction.
