### ISSUE TITLE
How can I use it to extract Spanish subtitles?

### ISSUE THREAD

**Issue by serena13** [wayneclub/Subtitle-Downloader#2]
How can I use it to extract Spanish subtitles (es-419)?

What command should I use?

Is it useful to extract forced subtitles  (es-419-forced)?

**Comment by wayneclub** [comment]
Hi,
I'd add English descriptions; please re-download the code.
Add -slang parameter, use comma to separate multiple languages.
`python subtitle_downloader.py [URL] -email [email] -password [password] -slang es-419`

Usually forced subtitles only several lines which translate non-native language, so it's not helpful.
If lots of people request forced subtitles, I'll add it.

**Comment by serena13** [comment]
> Hi, I'd add English descriptions; please re-download the code. Add -slang parameter, use comma to separate multiple languages. `python subtitle_downloader.py [URL] -email [email] -password [password] -slang es-419`
> 
> Usually forced subtitles only several lines which translate non-native language, so it's not helpful. If lots of people request forced subtitles, I'll add it.

Thank you so much
