### ISSUE TITLE
catchplay

### ISSUE THREAD

**Issue by xiaoxiaoliya** [wayneclub/Subtitle-Downloader#21]
[XstreamDL-2022-03-25_001455.log](https://github.com/wayneclub/Subtitle-Downloader/files/8343673/XstreamDL-2022-03-25_001455.log)
Hello, how should I download subtitles from this link?
https://www.catchplay.com/tw/watch/5bdaf363-34b2-4095-afd5-2609dbc2b968

**Comment by xiaoxiaoliya** [comment]
it looks encrypted

**Comment by xiaoxiaoliya** [comment]
I got the key, how do I get the subtitles? thanks

**Comment by xiaoxiaoliya** [comment]
I got the video and audio, but I can't download the subtitles.

**Comment by wayneclub** [comment]
All platform URL is description page (detail page), not watch page.
