### ISSUE TITLE
Add support for HBOMax

### ISSUE THREAD

**Issue by slthelion** [wayneclub/Subtitle-Downloader#22]
I want to thank you first for the script.
HBOGo it's not available in Europe anymore, only HBOMax.
Can you add support for emea region ? Subtitles are in vtt format.

**Comment by wayneclub** [comment]
> I want to thank you first for the script. HBOGo it's not available in Europe anymore, only HBOMax. Can you add support for emea region ? Subtitles are in vtt format.

Account needed, if you wish to add support with HBOMAX, please contact us.
