### ISSUE TITLE
请问这是网络问题吗？

### ISSUE THREAD

**Issue by xiaoxiaoliya** [wayneclub/Subtitle-Downloader#25]
nowe
https://github.com/wayneclub/Subtitle-Downloader 使用这个项目时，字幕没下载完就中断 下载下一个了
日志文件
[XstreamDL-2022-03-31_161451.log](https://github.com/xhlove/XstreamDL-CLI/files/8387420/XstreamDL-2022-03-31_161451.log)
![image](https://user-images.githubusercontent.com/94291982/161010145-8f7c6315-bcea-4beb-91d4-49d27c79543a.png)

**Comment by wayneclub** [comment]
Please retry.
If the problem is not solved, check the internet connection.
