### ISSUE TITLE
viu不能选择部分集数下载

### ISSUE THREAD

**Issue by chali26** [wayneclub/Subtitle-Downloader#28]
我使用viu下载字幕 只能全集下载 当我输入-e 1 选择部分集数 就出现下面的情况 不能下载[]
![Snipaste_2022-04-26_08-58-30](https://user-images.githubusercontent.com/73935991/165198194-2d5fcb2b-e982-4b1b-8cfc-e870a64edb07.png)
(url)

**Comment by wayneclub** [comment]
> 我使用viu下载字幕 只能全集下载 当我输入-e 1 选择部分集数 就出现下面的情况 不能下载[] ![Snipaste_2022-04-26_08-58-30](https://user-images.githubusercontent.com/73935991/165198194-2d5fcb2b-e982-4b1b-8cfc-e870a64edb07.png) (url)

Fixed
