### ISSUE TITLE
Failed to download friday's subtitle.

### ISSUE THREAD

**Issue by chan1108** [wayneclub/Subtitle-Downloader#30]
ip: 35.245.38.33 (US)
Traceback (most recent call last):
  File "subtitle_downloader.py", line 158, in <module>
    friday.main()
  File "/content/Subtitle-Downloader/services/friday.py", line 313, in main
    r'<h2 class=\"title-eng\">(.+)<\/h2>', res.text)[0].strip().replace('，', ',')
IndexError: list index out of range

**Comment by wayneclub** [comment]
> ip: 35.245.38.33 (US) Traceback (most recent call last): File "subtitle_downloader.py", line 158, in friday.main() File "/content/Subtitle-Downloader/services/friday.py", line 313, in main r'<h2 class="title-eng">(.+)</h2>', res.text)[0].strip().replace('，', ',') IndexError: list index out of range

Please provide download links or title

**Comment by chan1108** [comment]
> 

Friday update its website view. All titles can't be downloaded. 
eg:https://video.friday.tw/drama/detail/2130

**Comment by wayneclub** [comment]
> > 
> 
> Friday updated its website view. All titles can't be downloaded. eg:https://video.friday.tw/drama/detail/2130

Fixed
