### ISSUE TITLE
Help with Catchplay?

### ISSUE THREAD

**Issue by p1nkyy** [wayneclub/Subtitle-Downloader#31]
Hi sorry to open an issue, I'm a new to Phyton and I can't get this to work.
1. I installed Phyton.
2. I took the cookies and copied to `Subtitle-Downloader/configs/cookies`
3. Double click `install_requirements.bat`
4. Double click `Subtitle_Downloader.bat`
5. A cmd window appeared
6. Type in this command: `python subtitle_downloader.py https://www.catchplay.com/id-en/video/743c61f7-19a7-488d-910b-7d32a89bd841 -slang all` but doesn't work, said _unrecognized argument._

Screenshot: https://puu.sh/JcnWA/1ecc32f193.png

What did I do wrong? This film is a rental movie, I have paid for it. Does it need account info? If yes, I don't use e-mail but phone number, is it possible to be done? Can the software be used for rent movie? Thanks in advance.

EDIT:
Tried in Collab and it said `Out of services!` Does this mean it doesn't work for Catchplay?

**Comment by tonyhsie** [comment]
In your step 6, you just need to type the url only, not the "python subtitle_downloader.py https://www.catchplay.com/id-en/video/743c61f7-19a7-488d-910b-7d32a89bd841 -slang all".

Or you may ignore the "Subtitle_Downloader.bat", just type the whole "python ..." command in the cmd window.

**Comment by CoCoLaL** [comment]
i have the same question for this issues

like this:

1. Subtitle-Downloader (clash)
Screenshot:[ https://imgur.com/a/VEzZlzY](url)

2. Subtitle-Downloader
Screenshot: [https://imgur.com/a/LG0uuWp](url)

3. Collab
Screenshot: [https://imgur.com/a/O8y4vqB](url)

**Comment by p1nkyy** [comment]
> In your step 6, you just need to type the url only, not the "python subtitle_downloader.py https://www.catchplay.com/id-en/video/743c61f7-19a7-488d-910b-7d32a89bd841 -slang all".
> 
> Or you may ignore the "Subtitle_Downloader.bat", just open a cmd window, switch to the directory of " Subtitle-Downloader", then type the whole "python ..." command in it.

I used the template code given in Collab and still doesn't work. Asked around and someone said this works only for Catchplay Taiwan. May be I will wait for official reply from @wayneclub

**Comment by CCKNBC** [comment]
For the same problem, it is also available last week

@CoCoLaL #32

**Comment by wayneclub** [comment]
> > In your step 6, you just need to type the url only, not the "python subtitle_downloader.py https://www.catchplay.com/id-en/video/743c61f7-19a7-488d-910b-7d32a89bd841 -slang all".
> > Or you may ignore the "Subtitle_Downloader.bat", just open a cmd window, switch to the directory of " Subtitle-Downloader", then type the whole "python ..." command in it.
> 
> I used the template code given in Collab and still doesn't work. Asked around and someone said this works only for Catchplay Taiwan. May be I will wait for official reply from @wayneclub

CatchPlay script had been updated please execute locally not on Colab
