### ISSUE TITLE
Got error on Mac when system preferred language is set to English

### ISSUE THREAD

**Issue by techmovie** [wayneclub/Subtitle-Downloader#35]
> Subtitle-Downloader/utils/helper.py", line 30, in get_locale
    if 'zh' in current_locale:
TypeError: argument of type 'NoneType' is not iterable

OS: Apple M1 Pro 12.5.1

The reason due to this issue is the result of function ` locale.getdefaultlocale` is `None`

**Comment by wayneclub** [comment]
Thanks for reply, fixed and update
