### ISSUE TITLE
HBO Go Asia

### ISSUE THREAD

**Issue by liongtwap** [wayneclub/Subtitle-Downloader#38]
Hi, some weeks ago, I tried hbogoasia, and it worked...
but now, its error, like this =
{"code":500,"message":"Wrong Username or Password"}

Username & password is correct. Please fix it.
Thanks

**Comment by wayneclub** [comment]
> Hi, some weeks ago, I tried hbogoasia, and it worked... but now, its error, like this = {"code":500,"message":"Wrong Username or Password"}
> 
> Username & password is correct. Please fix it. Thanks

Which region of hbogoasia are you using?
