### ISSUE TITLE
UnicodeEncodeError on windows 

### ISSUE THREAD

**Issue by Covernel** [wayneclub/Subtitle-Downloader#4]
### UnicodeEncodeError: 'cp950' codec can't encode character '\u53d1' in position 0: illegal multibyte sequence
```python
# subtitle_tool.py
`def file_create(...)` missing `encoding='utf-8'`
```

### Disney+ return 404
```python
# disneyplus.py
m3u_sub = m3u8.load(os.path.join(base_url, media.uri))
```

windows used backslash to join, the result url contain specials character `\r` and inaccessible
`https://xxxx.com/ps01/disney/xxxxxx` + `r/composite_xxxxxx` = `https://xxxx.com/ps01/disney/xxxxxx` + `\` + `r/composite_xxxxxx`

**Comment by wayneclub** [comment]
Thanks for debugging.
I'd fixed the issues and updated the code.
