### ISSUE TITLE
Disney+ problem

### ISSUE THREAD

**Issue by slthelion** [wayneclub/Subtitle-Downloader#45]
{"errors":[{"code":"media.not-playable"}]}

**Comment by FROGYu** [comment]
{"errors":[{"code":"media.not-playable"}]}

**Comment by wayneclub** [comment]
Please provide more details next time such as which show or movie you are downloading. If Colab can't run it, please try to execute it locally.

**Comment by skittlesvampir** [comment]
I've executed the following command locally:

`python subtitle_downloader.py "https://www.disneyplus.com/de-de/series/malcolm-mittendrin/5mNQERYSP5YN" -s 1 -e 1`

Afterwards I get some metadata, followed by the following stream url and error codes:

`https://disney.playback.edge.bamgrid.com/media/16200ec2-8c09-4890-bab9-a2da0f62f020/scenarios/ctr-limited
{"errors":[{"code":"media.not-playable"}]}
{"errors":[{"code":"media.not-playable"}]}`

I didn't want to paste the whole log as it contained some private details. If you need more information, please tell me.

**Comment by wayneclub** [comment]
> I've executed the following command locally:
> 
> `python subtitle_downloader.py "https://www.disneyplus.com/de-de/series/malcolm-mittendrin/5mNQERYSP5YN" -s 1 -e 1`
> 
> Afterwards I get some metadata, followed by the following stream url and error codes:
> 
> `https://disney.playback.edge.bamgrid.com/media/16200ec2-8c09-4890-bab9-a2da0f62f020/scenarios/ctr-limited {"errors":[{"code":"media.not-playable"}]} {"errors":[{"code":"media.not-playable"}]}`
> 
> I didn't want to paste the whole log as it contained some private details. If you need more information, please tell me.

Disney Plus update API. Fixed, please re-download

**Comment by skittlesvampir** [comment]
Works great now, thank you so much!
(You can close this issue now btw)
