### ISSUE TITLE
老大，能否增加Disney+的Codec！

### ISSUE THREAD

**Issue by jump1r** [wayneclub/Subtitle-Downloader#46]
Disney+
正常情况下，英语字幕默认为 “English[CC]”，Codec是 en，此字幕为[sdh]，里面有很多提示音的英文解释，适合残障人士，本人也比较喜欢这种字幕，因为我可以用它来练习英语口语和听力。
现在麻烦了，Disney+在部分剧集中又增加了一种字幕“English”，这样就变成了，“English”，Codec是 en，而之前的“English[CC]”，Codec是 en-gb。

这样我输入命令下载，打上en-gb，结果说找不到这个字幕。。。
求老大帮忙，增加en-gb这个Codec行吗？因为我就喜欢这种[sdh]字幕，里面有很多细节描述，对我学英文有帮助。
拜托啦，我自己曾经尝试编辑源代码，但是技术太差，没法通过。谢谢喔~~~
^_^

![2023-02-17_182808](https://user-images.githubusercontent.com/12111290/219619762-02e3e159-fdd6-4191-8ca8-de1aed86efff.jpg)

**Comment by th5566** [comment]
或許你可以試試用腳本來抓字幕

例如
https://greasyfork.org/zh-CN/scripts/404223-disney-subtitles-downloader

**Comment by wayneclub** [comment]
已新增，目前會告訴你有哪些字幕可供下載
