### ISSUE TITLE
無法安裝 install_requirements.bat

### ISSUE THREAD

**Issue by UnflyableGoldfish** [wayneclub/Subtitle-Downloader#49]
打開install_requirements.bat時
顯示「 'pip' 不是內部或外部命令、可執行的程式或批次檔。」

**Comment by wayneclub** [comment]
> 打開install_requirements.bat時
> 
> 顯示「 'pip' 不是內部或外部命令、可執行的程式或批次檔。」

請先在Windows安裝[Python](https://www.python.org/downloads/windows/)

**Comment by UnflyableGoldfish** [comment]
> > 打開install_requirements.bat時
> > 顯示「 'pip' 不是內部或外部命令、可執行的程式或批次檔。」
> 
> 請先在Windows安裝[Python](https://www.python.org/downloads/windows/)

已經安裝了

**Comment by wayneclub** [comment]
> > > 打開install_requirements.bat時
> > > 顯示「 'pip' 不是內部或外部命令、可執行的程式或批次檔。」
> > 
> > 
> > 請先在Windows安裝[Python](https://www.python.org/downloads/windows/)
> 
> 已經安裝了

Python 版本請安裝3.10以上，若還有問題請查詢安裝python，這問題與本專案無關
