### ISSUE TITLE
【建議】添加指定集數字幕下載

### ISSUE THREAD

**Issue by daliali2088** [wayneclub/Subtitle-Downloader#5]
感謝大大的腳本很方便，
想問一下可否增加指定集數的字幕下載

**Comment by wayneclub** [comment]
Hi, this function will add in the future.

**Comment by daliali2088** [comment]
> Hi, this function will add in the future.

thanks a lot

**Comment by wayneclub** [comment]
Add custom download seasons and episodes
`python download_subtitle.py URL -s 1 -e 1-10`
`python download_subtitle.py URL -s 1 -e 1,3,5`
