### ISSUE TITLE
当-slang all的时候不下载

### ISSUE THREAD

**Issue by reedoris** [wayneclub/Subtitle-Downloader#54]
设置为某一种语言的时候可以下载，但设置为all的时候，寻找完字幕以后并不会下载， 直接显示按任意键退出

**Comment by reedoris** [comment]
我下载的是wetv的字幕中有Arabic，而软件列表中没有该语言，是否和这个有关系？

**Comment by reedoris** [comment]
试了一个只有简体中文、繁体中文和印尼语的视频，仍然在搜寻完以后就停止了，看来不是Arabic的问题

**Comment by wayneclub** [comment]
> 设置为某一种语言的时候可以下载，但设置为all的时候，寻找完字幕以后并不会下载， 直接显示按任意键退出

已修正，請重試，謝謝

**Comment by reedoris** [comment]
> > 设置为某一种语言的时候可以下载，但设置为all的时候，寻找完字幕以后并不会下载， 直接显示按任意键退出
> 
> 已修正，請重試，謝謝

现在可以了，谢谢
