### ISSUE TITLE
mewatch登入失败

### ISSUE THREAD

**Issue by gamekingv** [wayneclub/Subtitle-Downloader#55]
你好，在尝试mewatch登入提示{"error":"Invalid request"}，我手动测试脚本的api也是返回这个

**Comment by wayneclub** [comment]
> 你好，在尝试mewatch登入提示{"error":"Invalid request"}，我手动测试脚本的api也是返回这个

mewatch更新api，已更新程式，免費內容可正常獲取，付費內容需要訂閱帳號協助測試。

**Comment by gamekingv** [comment]
测试可行，非常感谢处理
