### ISSUE TITLE
viu not working

### ISSUE THREAD

**Issue by Jinni779** [wayneclub/Subtitle-Downloader#56]
https://www.viu.com/ott/th/th/vod/31916/Empress-Ki
<img width="783" alt="0c671c06-c1f0-452a-b732-453c692abb48" src="https://github.com/wayneclub/Subtitle-Downloader/assets/147328851/ce0f7479-5676-416f-862a-13b17ebbdb46">

**Comment by wayneclub** [comment]
> https://www.viu.com/ott/th/th/vod/31916/Empress-Ki

Viu.com update API.
Fixed, please re-download the project and retry.

**Comment by Jinni779** [comment]
Thank you. It works.
