### ISSUE TITLE
mewatch部分免费番剧需要登入才能获取字幕

### ISSUE THREAD

**Issue by gamekingv** [wayneclub/Subtitle-Downloader#57]
mewatch是否又改版了，比如说https://www.mewatch.sg/show/Ragna-Crimson-408490这个，在不登入情况下第三集提示rating restriction，前两集正常

**Comment by wayneclub** [comment]
> mewatch是否又改版了，比如说[https://www.mewatch.sg/show/Ragna-Crimson-408490这个，在不登入情况下第三集提示rating](https://www.mewatch.sg/show/Ragna-Crimson-408490%E8%BF%99%E4%B8%AA%EF%BC%8C%E5%9C%A8%E4%B8%8D%E7%99%BB%E5%85%A5%E6%83%85%E5%86%B5%E4%B8%8B%E7%AC%AC%E4%B8%89%E9%9B%86%E6%8F%90%E7%A4%BArating) restriction，前两集正常

meWATCH 目前登入有使用Google reCAPTCHA v2，防止自動登入，為了方便之後不論其更改登入模式，將程式直接改成使用profile token登入，profile token獲取方式請參閱README.md

1. 在瀏覽器登錄 [meWATCH](https://www.mewatch.sg/)
2. 選擇要下載的電影或連續劇
3. 在瀏覽器中打開`開發人員工具`（Windows：Ctrl + Shift + I 或 F12；macOS：⌘ + ⌥ + I。）
4. 重新整理網頁，在開發人員工具上選擇`網路`
5. 在篩選器中輸入 `https://www.mewatch.sg/api/account/profile`，找到profile api
6. 複製 profile api 中 Request Headers 的 profile token（X-Authorization）（不要包含 `Bearer`，profile token是"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJ"開頭）貼到 `Subtitle-Downloader/user_config.toml ([credentials.meWATCH] profile_token='')`
