### ISSUE TITLE
Missing "clientID" in www.myvideo.net.tw_cookies.txt.

### ISSUE THREAD

**Issue by RomaYun323** [wayneclub/Subtitle-Downloader#61]
登入my video後下載下來的cookies無法下載字幕
Missing "clientID" in www.myvideo.net.tw_cookies.txt.
Please login to streaming services and renew cookies...
是我哪裡用錯了嗎？

**Comment by wayneclub** [comment]
> 登入my video後下載下來的cookies無法下載字幕 Missing "clientID" in [www.myvideo.net.tw_cookies.txt](http://www.myvideo.net.tw_cookies.txt). Please login to streaming services and renew cookies... 是我哪裡用錯了嗎？

官方cookies更新，已更新程式

**Comment by RomaYun323** [comment]
> > 登入my video後下載下來的cookies無法下載字幕 Missing "clientID" in [www.myvideo.net.tw_cookies.txt](http://www.myvideo.net.tw_cookies.txt). Please login to streaming services and renew cookies... 是我哪裡用錯了嗎？
> 
> 官方cookies更新，已更新程式

 正常下載了，感謝
