### ISSUE TITLE
请问有计划支持hulu和peacock吗？

### ISSUE THREAD

**Issue by iqiyiqiyuvr** [wayneclub/Subtitle-Downloader#65]
请问有计划支持hulu和peacock吗？
谢谢！

**Comment by wayneclub** [comment]
> 请问有计划支持hulu和peacock吗？ 谢谢！

需要測試帳號開發，若有需要可以私聊

**Comment by probiome** [comment]
Hi. I use this Python package via Colab. When I try to download subtitles from Apple TV, sometimes I see only zh-Hant subtitles, even if another subtitles are available.

For example: Simulant (2023)

Link: https://tv.apple.com/tr/movie/simulant/umc.cmc.38jwhekca6uyrvey6zs3n0xkk

Turkish subtitle is available for this movie. But, it downloads zh-Hant subtitles only.

How can I fix this issue? Thank you.

![Screenshot 2023-12-03 075937](https://github.com/wayneclub/Subtitle-Downloader/assets/130521636/e3d8f5d9-66ad-4718-97fe-d7aa89112c03)

**Comment by vleaf0210** [comment]
> 안녕. 저는 Colab을 통해 이 Python 패키지를 사용합니다. Apple TV에서 자막을 다운로드하려고 하면 다른 자막이 있음에도 불구하고 zh-Hant 자막만 표시되는 경우가 있습니다.
> 
> 예: 시뮬런트(2023)
> 
> 링크: https://tv.apple.com/tr/movie/simulant/umc.cmc.38jwhekca6uyrvey6zs3n0xkk
> 
> 이 영화에는 터키어 자막을 사용할 수 있습니다. 하지만 zh-Hant 자막만 다운로드됩니다.
> 
> 이 문제를 어떻게 해결할 수 있나요? 감사합니다.
> 
> ![스크린샷 2023-12-03 075937](https://private-user-images.githubusercontent.com/130521636/287498087-e3d8f5d9-66ad-4718-97fe-d7aa89112c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1ODY4NjQsIm5iZiI6MTcwMTU4NjU2NCwicGF0aCI6Ii8xMzA1MjE2MzYvMjg3NDk4MDg3LWUzZDhmNWQ5LTY2YWQtNDcxOC05N2ZlLWQ3YWE4OTExMmMwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwNjU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmY3MWI4Y2FjMjQzMzI0OTBjYzFlNDZkZDEzYjQ2MTZjMjg3MzI2ODM5NTU4MzIyNzJhZTNkM2FkMzYyMTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AgpeKp6vUPRt38M-thjALwBL2wrVhOPKJe4VuhJaU30)

I've had the same problem.

**Comment by probiome** [comment]
But, this script worked for me: https://greasyfork.org/en/scripts/422823-itunes-subtitle-downloader

**Comment by wayneclub** [comment]
> > 안녕. 저는 Colab을 통해 이 Python 패키지를 사용합니다. Apple TV에서 자막을 다운로드하려고 하면 다른 자막이 있음에도 불구하고 zh-Hant 자막만 표시되는 경우가 있습니다.
> > 예: 시뮬런트(2023)
> > 링크: https://tv.apple.com/tr/movie/simulant/umc.cmc.38jwhekca6uyrvey6zs3n0xkk
> > 이 영화에는 터키어 자막을 사용할 수 있습니다. 하지만 zh-Hant 자막만 다운로드됩니다.
> > 이 문제를 어떻게 해결할 수 있나요? 감사합니다.
> > ![스크린샷 2023-12-03 075937](https://private-user-images.githubusercontent.com/130521636/287498087-e3d8f5d9-66ad-4718-97fe-d7aa89112c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1ODY4NjQsIm5iZiI6MTcwMTU4NjU2NCwicGF0aCI6Ii8xMzA1MjE2MzYvMjg3NDk4MDg3LWUzZDhmNWQ5LTY2YWQtNDcxOC05N2ZlLWQ3YWE4OTExMmMwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwNjU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmY3MWI4Y2FjMjQzMzI0OTBjYzFlNDZkZDEzYjQ2MTZjMjg3MzI2ODM5NTU4MzIyNzJhZTNkM2FkMzYyMTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AgpeKp6vUPRt38M-thjALwBL2wrVhOPKJe4VuhJaU30)
> 
> I've had the same problem.

Same issue as https://github.com/wayneclub/Subtitle-Downloader/issues/67
You can edit the subtitle language in `user_config.toml`

**Comment by wayneclub** [comment]
> > > I've already made this edit before. However, nothing has changed. The problem still continues. I don't know what is the source of the problem?
> > 
> > 
> > Fixed, download project and retry.
> 
> Simulant (2023)
> 
> 抱歉，您尚未購買此部電影
> 
> That's what I see.

The subtitle from AppleTVPlus is based on the storefront from your Apple account. If your Apple account is from Taiwan this movie only provides Traditional Chinese. 

Use debug mode and provide the debug log

```bash
python subtitle downloader https://tv.apple.com/tr/movie/simulant/umc.cmc.38jwhekca6uyrvey6zs3n0xkk -d
```

**Comment by wayneclub** [comment]
> > > > > I've already made this edit before. However, nothing has changed. The problem still continues. I don't know what is the source of the problem?
> > > > 
> > > > 
> > > > Fixed, download project and retry.
> > > 
> > > 
> > > Simulant (2023)
> > > 抱歉，您尚未購買此部電影
> > > That's what I see.
> > 
> > 
> > The subtitle from AppleTVPlus is based on the storefront from your Apple account. If your Apple account is from Taiwan this movie only provides Traditional Chinese.
> > Use debug mode and provide the debug log
> > ```shell
> > python subtitle_downloader.py https://tv.apple.com/tr/movie/simulant/umc.cmc.38jwhekca6uyrvey6zs3n0xkk -d
> > ```
> 
> The previous version of this app at least worked for movies with multiple languages. Now it has stopped completely. I tried it on movies that worked before, but I always encounter the same error: 抱歉，您尚未購買此部電影
> 
> I signed in to the US location on Apple TV. Otherwise, Apple TV is not available in Turkey.

Please provide the full log file...
If you use the US Apple TV profile, please get the URL from the US AppleTV+ store, not Turkey...

**Comment by wayneclub** [comment]
> [app (1).log](https://github.com/wayneclub/Subtitle-Downloader/files/13542301/app.1.log)

Please provide the log file from Subtitle-Downloader in Subtitle-Downloader's log folder (Subtitle-Downloader_2023-12-XX_XX-XX-XX.log)

**Comment by wayneclub** [comment]
> > [app (1).log](https://github.com/wayneclub/Subtitle-Downloader/files/13542301/app.1.log)
> 
> Please provide the log file from Subtitle-Downloader in Subtitle-Downloader's log folder (Subtitle-Downloader_2023-12-XX_XX-XX-XX.log)

Also, could you make sure your account has purchased the video? Currently, the service is designed for users who subscribe to AppleTV+ or purchase or rent iTunes movies.

**Comment by probiome** [comment]
> > [app (1).log](https://github.com/wayneclub/Subtitle-Downloader/files/13542301/app.1.log)
> 
> Please provide the log file from Subtitle-Downloader in Subtitle-Downloader's log folder (Subtitle-Downloader_2023-12-XX_XX-XX-XX.log)

I use Colab to run this application. The log folder is empty. There's nothing there.

![Screenshot 2023-12-04 091734](https://github.com/wayneclub/Subtitle-Downloader/assets/130521636/7a424ffe-a779-4fd2-96bf-dab004f39a1f)

**Comment by probiome** [comment]
> > > [app (1).log](https://github.com/wayneclub/Subtitle-Downloader/files/13542301/app.1.log)
> > 
> > 
> > Please provide the log file from Subtitle-Downloader in Subtitle-Downloader's log folder (Subtitle-Downloader_2023-12-XX_XX-XX-XX.log)
> 
> Also, could you make sure your account has purchased the video? Currently, the service is designed for users who subscribe to AppleTV+ or purchase or rent iTunes movies.

As I said, in the version before the latest version you published, I was able to download at least all the subtitles available in movies containing multiple subtitles. The script called iTunes Subtitle Downloader downloads all subtitles on Apple TV without requiring any membership. I think you must have made some bugs in the latest version.

**Comment by wayneclub** [comment]
> > > > [app (1).log](https://github.com/wayneclub/Subtitle-Downloader/files/13542301/app.1.log)
> > > 
> > > 
> > > Please provide the log file from Subtitle-Downloader in Subtitle-Downloader's log folder (Subtitle-Downloader_2023-12-XX_XX-XX-XX.log)
> > 
> > 
> > Also, could you make sure your account has purchased the video? Currently, the service is designed for users who subscribe to AppleTV+ or purchase or rent iTunes movies.
> 
> As I said, in the version before the latest version you published, I was able to download at least all the subtitles available in movies containing multiple subtitles. The script called iTunes Subtitle Downloader downloads all subtitles on Apple TV without requiring any membership. I think you must have made some bugs in the latest version.

Yes. I know iTunes Subtitle Downloader. This script was designed differently because that script depends on js load and gets m3u8 hsl URL. You will find out not all the movies and TV episodes can be downloaded.

**Comment by vleaf0210** [comment]
Did you follow the Installation Guide on README.md?

**Comment by probiome** [comment]
> Did you follow the Installation Guide on README.md?

Yes, but it didn't work. I have no idea why. I am new for Python packages. I ran "Subtitle-Downloader" on Phython and it worked for me. But, it downloads zh-Hant subtitles only for some movies, and it downsloads all substitles when multi subtitles are available for some movies. I coundn't fix it. Even, its owner. :))

**Comment by vleaf0210** [comment]
Which movie do you need subtitles for? Give me an Apple TV link and I'll see if it's possible.

**Comment by probiome** [comment]
> What movie subtitles do you need? Give me an Apple TV link and I'll see if it's possible.

Knock at the Cabin: https://tv.apple.com/us/movie/knock-at-the-cabin/umc.cmc.7fetnok7ou3e2dhp9808fprnt

**Comment by probiome** [comment]
> https://file.io/EjqdAOFM0a3z

That's nice. But, I can't run this Python app. How did you install and run this Python app?

**Comment by probiome** [comment]
> python3 -m pip install -e git+https://github.com/MichaelYochpaz/iSubRip.git#egg=isubrip

I get errors:

![iSubrip git](https://github.com/wayneclub/Subtitle-Downloader/assets/130521636/49ecf093-4877-41d3-b2d0-0a7a681bba76)

**Comment by probiome** [comment]
> > > python3 -m pip install -e git+https://github.com/MichaelYochpaz/iSubRip.git#egg=isubrip
> > 
> > 
> > Okay, done. But, still have the same issue.
> 
> Do you have a screenshot?

![Environment variable](https://github.com/wayneclub/Subtitle-Downloader/assets/130521636/c9374412-f9b7-4ee4-9362-bcaf58516c8c)
![cmd isubrip](https://github.com/wayneclub/Subtitle-Downloader/assets/130521636/bf7768bf-af5b-4b61-8553-b6ed6cadd24d)

**Comment by probiome** [comment]
By the way, I have already downloaded "iSubRip.git" from https://github.com/MichaelYochpaz/iSubRip.git

**Comment by vleaf0210** [comment]
Clear '\git.exe' from the text above and it will work.
C:\Users\mehme\AppData\Local\GitHubDesktop\app-3.3.5\resources\app\git\cmd

**Comment by vleaf0210** [comment]
Now try again to see if it works well.

**Comment by vleaf0210** [comment]
Add the following folder to PATH.
C:\Users\mehme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts

**Comment by probiome** [comment]
> ![스크린샷 2023-12-04 223951](https://private-user-images.githubusercontent.com/59910113/287715608-fbb4a3f5-061b-4f02-874e-725286caf84e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTc1NzYsIm5iZiI6MTcwMTY5NzI3NiwicGF0aCI6Ii81OTkxMDExMy8yODc3MTU2MDgtZmJiNGEzZjUtMDYxYi00ZjAyLTg3NGUtNzI1Mjg2Y2FmODRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEzNDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NjY2NmRhMTQ5YTI2YTM2YTk3NWUxYzRiMDA5MjkzNjRlMDRiMDQzMDJiZGFhOGJlNDM4MjMxMzhkMzg4OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55Ud7kp0H5JpbJG6Xw_nHufn3y3krkJ7bFUdJ7Wg4Kg)



> Add the following folder to 'PATH'. C:\Users\mehme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts

Solved! I copied isubrip.exe and pasted in C:\Users\mehme\AppData\Local\GitHubDesktop\app-3.3.5\resources\app\git\cmd

![Fixed](https://github.com/wayneclub/Subtitle-Downloader/assets/130521636/baf81657-0bd7-4512-ae45-c8e0378a237b)

Thanks for your help. 🥇 :)) :
