### ISSUE TITLE
Hi. I use this Python package via Colab. When I try to download subtitles from Apple TV, sometimes I see only zh-Hant subtitles, even if another subtitles are available.

### ISSUE THREAD

**Issue by wayneclub** [wayneclub/Subtitle-Downloader#67]
Hi. I use this Python package via Colab. When I try to download subtitles from Apple TV, sometimes I see only zh-Hant subtitles, even if another subtitles are available.

For example: Simulant (2023)

Link: https://tv.apple.com/tr/movie/simulant/umc.cmc.38jwhekca6uyrvey6zs3n0xkk

Turkish subtitle is available for this movie. But, it downloads zh-Hant subtitles only.

How can I fix this issue? Thank you.

![Screenshot 2023-12-03 075937](https://github.com/wayneclub/Subtitle-Downloader/assets/130521636/e3d8f5d9-66ad-4718-97fe-d7aa89112c03)

_Originally posted by @probiome in https://github.com/wayneclub/Subtitle-Downloader/issues/65#issuecomment-1837369982_

**Comment by wayneclub** [comment]
> > ```
> >           Hi. I use this Python package via Colab. When I try to download subtitles from Apple TV, sometimes I see only zh-Hant subtitles, even if another subtitles are available.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 예: 시뮬런트(2023)
> > 링크: https://tv.apple.com/tr/movie/simulant/umc.cmc.38jwhekca6uyrvey6zs3n0xkk
> > 이 영화에는 터키어 자막을 사용할 수 있습니다. 하지만 zh-Hant 자막만 다운로드됩니다.
> > 이 문제를 어떻게 해결할 수 있나요? 감사합니다.
> > ![스크린샷 2023-12-03 075937](https://private-user-images.githubusercontent.com/130521636/287498087-e3d8f5d9-66ad-4718-97fe-d7aa89112c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NzM3MDQsIm5iZiI6MTcwMTY3MzQwNCwicGF0aCI6Ii8xMzA1MjE2MzYvMjg3NDk4MDg3LWUzZDhmNWQ5LTY2YWQtNDcxOC05N2ZlLWQ3YWE4OTExMmMwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQwNzAzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTc5MGExZmMyZmYzZDY5NmMyODViMDQ0NDc0ZjFkZmFmNjhmMzdlYzhiNmUzNzE4YjQ0MWNmYmU1OGY3MDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2cabvy0ofeug9WBoPNFAdmUoyrSUh2k2pSo64wM4DjY)
> > _원래 게시자:@probiome[#65(댓글](https://github.com/wayneclub/Subtitle-Downloader/issues/65#issuecomment-1837369982) )_
> 
> https://www.file.io/MxWc/download/SDyirJmPfuXG I got it using a different tool. I couldn't download Turkish subtitles with this tool. I don't know why.

Yes. I know iTunes Subtitle Downloader. This script was designed differently because that script depends on js load and gets the m3u8 HSL URL. You will find out not all the movies and TV episodes can be downloaded. As I mentioned in the readme, this script has some prerequisites. You will need the subscription.

**Comment by vleaf0210** [comment]
> Finally, fixed it. :))
> 
> ![Subtitle language](https://private-user-images.githubusercontent.com/130521636/287783873-dc15b671-8411-4831-9f28-bbe398bba762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTI3NDksIm5iZiI6MTcwMTcxMjQ0OSwicGF0aCI6Ii8xMzA1MjE2MzYvMjg3NzgzODczLWRjMTViNjcxLTg0MTEtNDgzMS05ZjI4LWJiZTM5OGJiYTc2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNzU0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDIwY2YxMWUyNWIzODc5NTUzNjI4OGJiYmI2NGE1OTUxMjlmNTQ5ZTJmNTBlZTFkMzdiMjllZGRkYTk0ZmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fSWqyEveAq60PGsoJsudLukdTQg_1j_0McZvOsIXIJE)

How did you fix it?

**Comment by probiome** [comment]
I opened "AppleTVPlus.toml" with Notepad. And I changed these:

sf = '143480'                                   # "storefront", country | 143441: US, 143444: GB, 143470:TW, 143480:TR

I added Turkey's storefront ID as sf = '143480' 

I opened user_config.toml with Notepad and changed default-language for subtitles as "all".

[subtitles]
default-language = 'all'

That's all. :)

**Comment by probiome** [comment]
Get a country code from Apple's StoreFront IDs: https://gist.github.com/theiostream/5871770

You may need these codes someday.

**Comment by vleaf0210** [comment]
Oh, Thank you.
