### ISSUE TITLE
VIKI Support

### ISSUE THREAD

**Issue by AdzeB** [wayneclub/Subtitle-Downloader#7]
Hey, First of all, I just wanted to say incredible work, this is amazing

I wanted to ask if you could add VIKI subtitles also?

Thanks

**Comment by moyuaa** [comment]
Thank you very much, I tried the subtitles of viu in Singapore and can't download it, will it be added in the future?

**Comment by wayneclub** [comment]
> Thank you very much, I tried the subtitles of viu in Singapore and can't download it, will it be added in the future?

Support Viu.com in Singapore without VPN.
Please notice some dramas in Singapore don't support Traditional Chinese and you have to select "zh-Hans" for Simplified Chinese.

**Comment by wayneclub** [comment]
> Hey, First of all, I just wanted to say incredible work, this is amazing
> 
> I wanted to ask if you could add VIKI subtitles also?
> 
> Thanks

Viki will be added in the future.
