### ISSUE TITLE
對viu的支持失效

### ISSUE THREAD

**Issue by senchuanqianxia** [wayneclub/Subtitle-Downloader#70]
<img width="757" alt="{54D76063-5CE8-4f68-9652-F7839E95040E}" src="https://github.com/wayneclub/Subtitle-Downloader/assets/151311089/467290af-a0f5-43fe-97cf-85fb1469bc06">

**Comment by wayneclub** [comment]
> <img alt="{54D76063-5CE8-4f68-9652-F7839E95040E}" width="757" src="https://private-user-images.githubusercontent.com/151311089/291801677-467290af-a0f5-43fe-97cf-85fb1469bc06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDUyNzAsIm5iZiI6MTcwNDgwNDk3MCwicGF0aCI6Ii8xNTEzMTEwODkvMjkxODAxNjc3LTQ2NzI5MGFmLWEwZjUtNDNmZS05N2NmLTg1ZmIxNDY5YmMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMjU2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODQ1MTU5NDdhY2FiM2Q5ZjBjN2MxNWFhYTg5MGZiMmY0NDI5YzdhN2ZkN2FjNWY3ZTkyNDhmZmZlMDlhMTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BZlj0yRF4hmHa5DHCsib75ZtJMgPFx6asKvQWSIlTWM">

Viu更改網站部分內容，已修正更新
