### ISSUE TITLE
when i run the install_requirements.bat,got this error

### ISSUE THREAD

**Issue by frankwu8765** [wayneclub/Subtitle-Downloader#71]
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by wayneclub** [comment]
> Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [6 lines of output]
> 
> ```
>   Cargo, the Rust package manager, is not installed or is not on PATH.
>   This package requires Rust and Cargo to compile extensions. Install it through
>   the system's package manager or via https://rustup.rs/
> 
>   Checking for Rust toolchain....
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

Which Python version are you using? Please use 3.11 or 3.10
