### ISSUE TITLE
Failed to download subtitles from the Mewatch website.

### ISSUE THREAD

**Issue by moyuaa** [wayneclub/Subtitle-Downloader#73]
![Image 3mewatch](https://github.com/wayneclub/Subtitle-Downloader/assets/96807068/706bce80-9489-4055-bf79-43f378106b8e)

https://www.mewatch.sg/show/A-Waiting-Bride-420691

**Comment by wayneclub** [comment]
Access Token was expired. Please login to mewatch.sg and get the new access token.

1. Login to [meWATCH](https://www.mewatch.sg/) on the browser.
2. Select a movie or series you want to download
3. Open the `devtools` in the browser (Windows: Ctrl + Shift + I or F12; macOS: ⌘ + ⌥ + I.)
4. Refresh the page and select `Network` on `devtools`
5. Type `https://www.mewatch.sg/api/account/profile` in the filter to find the profile api
6. Copy profile token (X-Authorization) from profile API Request Headers (Do not include `Bearer`, the profile token starts with `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJ`) and paste in `Subtitle-Downloader/user_config.toml ([credentials.meWATCH] profile_token='')`.
