### ISSUE TITLE
Failed to download subtitles from any site

### ISSUE THREAD

**Issue by yuzukiss** [wayneclub/Subtitle-Downloader#74]
![微信截图_20240130103856](https://github.com/wayneclub/Subtitle-Downloader/assets/61487971/8b9a6578-57bb-41c8-a820-d73a8c121d9c)
![微信截图_20240130103914](https://github.com/wayneclub/Subtitle-Downloader/assets/61487971/a71f42c1-50d6-4758-89b1-86cc2d7cdcd6)
无论我下载哪个网站的字幕，都被定位去friday video然后报错。不知道是为什么呢

**Comment by wayneclub** [comment]
> ![微信截图_20240130103856](https://private-user-images.githubusercontent.com/61487971/300662450-8b9a6578-57bb-41c8-a820-d73a8c121d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjY4NDksIm5iZiI6MTcwNjYyNjU0OSwicGF0aCI6Ii82MTQ4Nzk3MS8zMDA2NjI0NTAtOGI5YTY1NzgtNTdiYi00MWM4LWE4MjAtZDczYThjMTIxZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE0NTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OGM2N2IzMmU1N2ExMTcxMTY4YzlkNmIxOTAzMDBjMDdkMWRiY2FlZDU0OTE2NWJmMjg0NDAwNjhjZTYxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KhnkiAw0hhJNsroHLQXdridVKrcVOVFdcbPp3lWc6Ko) ![微信截图_20240130103914](https://private-user-images.githubusercontent.com/61487971/300662457-a71f42c1-50d6-4758-89b1-86cc2d7cdcd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjY4NDksIm5iZiI6MTcwNjYyNjU0OSwicGF0aCI6Ii82MTQ4Nzk3MS8zMDA2NjI0NTctYTcxZjQyYzEtNTBkNi00NzU4LTg5YjEtODZjYzJkN2NkY2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE0NTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODZjZjE5N2M1ZWI5NDRlMTQ3YjYyOWQ2OWEyMmUyNmQ3NWViYTJmZTE3NzlkMWVhMGJiNmVkZGU5YjMwNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uVh9L32x77ZzDMoRcNKNaYxrPSeJRYFY7a5w1zwPI94) 无论我下载哪个网站的字幕，都被定位去friday video然后报错。不知道是为什么呢

測試了Windows Mac Linux 皆無以上問題
請使用python 指令測試
`python subtitle_downloader.py URL`
