### ISSUE TITLE
Failed to download subtitles Thai from iq.com

### ISSUE THREAD

**Issue by Jinni779** [wayneclub/Subtitle-Downloader#76]
url https://www.iq.com/album/your-lie-in-april-2014-2g6mip8tge9?lang=th_th

![image](https://github.com/wayneclub/Subtitle-Downloader/assets/147328851/02f7a0a5-f0e7-424c-a168-db418d150ea9)

**Comment by wayneclub** [comment]
> url https://www.iq.com/album/your-lie-in-april-2014-2g6mip8tge9?lang=th_th
> 
> ![image](https://private-user-images.githubusercontent.com/147328851/302142474-02f7a0a5-f0e7-424c-a168-db418d150ea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDYwNTAsIm5iZiI6MTcwODEwNTc1MCwicGF0aCI6Ii8xNDczMjg4NTEvMzAyMTQyNDc0LTAyZjdhMGE1LWYwZTctNDI0Yy1hMTY4LWRiNDE4ZDE1MGVhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxNzQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTJlMTgwNjA4ZDgwZDQxZGQzYjZmN2E4NzFiNjhjZWIxMDEwNDgwMGNhMDNjYzkxMGJkN2NiYmYzOTg3ZTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VRPKRMLmoY62snCogTnFbW8gSatJJRrpz0FRn2zqmKk)

Edit `user-config.toml`, default-language to all
[subtitles]
default-language = 'all'  # all/en/zh-Hant/zh-Hans/zh-HK/ja/ko
