### ISSUE TITLE
WETV Error

### ISSUE THREAD

**Issue by downftn01** [wayneclub/Subtitle-Downloader#81]
The error i have is when download Battle Through The Heavens. it is normal whene download season regular but when download special episode the error showing.

This is the error -->
Battle Through The Heavens Special 3: Three Years of Pledge

第 1 季 共有：13 集	下載全集
---------------------------------------------------------------
尋找 Battle.Through.The.Heavens.Special.3.Three.Years.of.Pledge.S01E01.WEB-DL.WeTV.vtt ...
getinfo_callback_941137({"ip":"34.125.138.175","s":"f","em":80,"exem":30001002,"msg":"您所在的地區因版權原因無法播放，去看看其他影片吧","exinfo":"美国---未知","code":""})

Whenever i download special 1,2,3 it wont downloaded but when ragular season it works
Hope you cant fix it.

**Comment by wayneclub** [comment]
> Battle.Through.The.Heavens.Special.3.

Hi, please execute the script locally. (Not local, or you have to use NordVPN on the cloud) 
Colab environment is in the US. So the show is unavailable.

[Battle.Through.The.Heavens.Special.3.Three.Years.of.Pledge.S01.WEB-DL.WeTV.zip](https://github.com/wayneclub/Subtitle-Downloader/files/14638059/Battle.Through.The.Heavens.Special.3.Three.Years.of.Pledge.S01.WEB-DL.WeTV.zip)
