### ISSUE TITLE
Linetv最新一集字幕无法正常获取

### ISSUE THREAD

**Issue by gamekingv** [wayneclub/Subtitle-Downloader#82]
Linetv最新一集的番剧字幕无法正常获取，比如[https://www.linetv.tw/drama/15731/eps/10](https://www.linetv.tw/drama/15731/eps/10)，前面9集都是正常的，但第10集根据脚本的api获取会提示AccessDenied，但实际字幕确实存在，有看到有大佬抽取了出来，是否Linetv做了什么变更导致？

**Comment by wayneclub** [comment]
> Linetv最新一集的番剧字幕无法正常获取，比如https://www.linetv.tw/drama/15731/eps/10，前面9集都是正常的，但第10集根据脚本的api获取会提示AccessDenied，但实际字幕确实存在，有看到有大佬抽取了出来，是否Linetv做了什么变更导致？

LineTV API更新，已修正

**Comment by gamekingv** [comment]
非常感谢修正
