### ISSUE TITLE
想請問一下 linetv 下載字幕

### ISSUE THREAD

**Issue by gprs1234** [wayneclub/Subtitle-Downloader#86]
之前有在用大大的 因電腦重新安裝所以重新下載後

它顯示

C:\Users\agarh\Subtitle-Downloader-main>python subtitle_downloader.py https://www.linetv.tw/drama/16008/eps/1

7人的復活 Season 1

Season 1 total: 16 episode(s)   update to episode 1     download all episodes
---------------------------------------------------------------
{'code': 4004, 'message': '尚未開放免費觀看', 'countryCode': 228}

我本身有linetv 的VIP

我在configs 裡面有看到 linetv 的 toml裡面的內容是

credentials = '請問這個是要填下面圖片哪一個'
required = '請問這個是要填下面圖片哪一個'

app_id = '062097f1b1f34e11e7f82aag22000aee'   (這裡要填下面圖片哪一個??)

[api]
manifest = 'https://www.linetv.tw/api/part/{drama_id}/eps/{episode_index}/part?appId={app_id}&device=desktop_web&chocomemberId={member_id}&productType=VOD'
sub_1 = 'https://s3-ap-northeast-1.amazonaws.com/tv-aws-media-convert-input-tokyo/subtitles/{drama_id}/{drama_id}-eps-{episode_name}.vtt'
sub_2 = 'https://choco-tv.s3.amazonaws.com/subtitle/{drama_id}-{drama_name}/{drama_id}-eps-{episode_name}.vtt'

![image](https://github.com/wayneclub/Subtitle-Downloader/assets/132209168/cf0e22b2-fc1e-4cfb-b187-d9bf432ed361)

![image](https://github.com/wayneclub/Subtitle-Downloader/assets/132209168/e9b309c2-4d3e-4511-ae69-99c39bd2f1ad)

![image](https://github.com/wayneclub/Subtitle-Downloader/assets/132209168/e9d9a437-e022-4540-b430-7fdb64b0d1b3)

**Comment by wayneclub** [comment]
> 之前有在用大大的 因電腦重新安裝所以重新下載後
> 
> 它顯示
> 
> C:\Users\agarh\Subtitle-Downloader-main>python subtitle_downloader.py https://www.linetv.tw/drama/16008/eps/1
> 
> 7人的復活 Season 1
> 
> ## Season 1 total: 16 episode(s) update to episode 1 download all episodes
> {'code': 4004, 'message': '尚未開放免費觀看', 'countryCode': 228}
> 
> 我本身有linetv 的VIP
> 
> 我在configs 裡面有看到 linetv 的 toml裡面的內容是
> 
> credentials = '請問這個是要填下面圖片哪一個' required = '請問這個是要填下面圖片哪一個'
> 
> app_id = '062097f1b1f34e11e7f82aag22000aee' (這裡要填下面圖片哪一個??)
> 
> [api] manifest = '[https://www.linetv.tw/api/part/{drama_id}/eps/{episode_index}/part?appId={app_id}&device=desktop_web&chocomemberId={member_id}&productType=VOD](https://www.linetv.tw/api/part/%7Bdrama_id%7D/eps/%7Bepisode_index%7D/part?appId=%7Bapp_id%7D&device=desktop_web&chocomemberId=%7Bmember_id%7D&productType=VOD)' sub_1 = '[https://s3-ap-northeast-1.amazonaws.com/tv-aws-media-convert-input-tokyo/subtitles/{drama_id}/{drama_id}-eps-{episode_name}.vtt](https://s3-ap-northeast-1.amazonaws.com/tv-aws-media-convert-input-tokyo/subtitles/%7Bdrama_id%7D/%7Bdrama_id%7D-eps-%7Bepisode_name%7D.vtt)' sub_2 = '[https://choco-tv.s3.amazonaws.com/subtitle/{drama_id}-{drama_name}/{drama_id}-eps-{episode_name}.vtt](https://choco-tv.s3.amazonaws.com/subtitle/%7Bdrama_id%7D-%7Bdrama_name%7D/%7Bdrama_id%7D-eps-%7Bepisode_name%7D.vtt)'
> 
> ![image](https://private-user-images.githubusercontent.com/132209168/318167557-6ae9360b-2400-4405-8775-8b651477413f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzM4OTAsIm5iZiI6MTcxMTc3MzU5MCwicGF0aCI6Ii8xMzIyMDkxNjgvMzE4MTY3NTU3LTZhZTkzNjBiLTI0MDAtNDQwNS04Nzc1LThiNjUxNDc3NDEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwNDM5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWEwYTVkOTFiOTc1YzI4NGM5NWI1NDY4ODhmMWQ0NWU5ZTRmOGMyMWM2NzRlOWEzMjM0NDZhOGFmYWQ5OTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.krDT0grwG57q4e2Ol9c8jB1JyYwOr8p4SOn4WRrbOhg) ![image](https://private-user-images.githubusercontent.com/132209168/318167568-62417697-4f3f-46e4-bb7c-675a77a87d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzM4OTAsIm5iZiI6MTcxMTc3MzU5MCwicGF0aCI6Ii8xMzIyMDkxNjgvMzE4MTY3NTY4LTYyNDE3Njk3LTRmM2YtNDZlNC1iYjdjLTY3NWE3N2E4N2Q5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwNDM5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjUyMmExMGY3ODZlODM4YmE2ZDUyMWFlMzIzOTA5Y2I4OTk4ODgzM2MyMTM2ZjYyYjJlNWViODZjMjE4MjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jK5SVWZdxRc13zX4OCg6UrW7Hc7Wh8Lj_Tust4ImnJY)

都不用更改，只要在linetv登入後將cookies放入cookies的資料夾即可

**Comment by gprs1234** [comment]
![image](https://github.com/wayneclub/Subtitle-Downloader/assets/132209168/19f72e52-9f29-4f3a-8590-c023ac372e64)

我照做
然後把所有可能的方式都放在裡面還是一樣
下載後檔案名稱不變的也放進去
改變成cookie.txt也是

**Comment by wayneclub** [comment]
> ![image](https://private-user-images.githubusercontent.com/132209168/318168752-19f72e52-9f29-4f3a-8590-c023ac372e64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDA4MjgsIm5iZiI6MTcxMTk0MDUyOCwicGF0aCI6Ii8xMzIyMDkxNjgvMzE4MTY4NzUyLTE5ZjcyZTUyLTlmMjktNGYzYS04NTkwLWMwMjNhYzM3MmU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMzAyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTg2NGFiMWE4Yjg5MDgzNDFhYTgyNWVmZGQ5NDE4ODQxODQ4ZWY0YTBhZDdkNzI3NGI2MGU1MDNhN2FlNmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kNtFwoGa3YxBys86yq8blqQ9eRBkEYTQSeHI74ZlOUk) ![image](https://private-user-images.githubusercontent.com/132209168/318168888-cc091794-5da5-4091-96e7-1b8b2bce84fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDA4MjgsIm5iZiI6MTcxMTk0MDUyOCwicGF0aCI6Ii8xMzIyMDkxNjgvMzE4MTY4ODg4LWNjMDkxNzk0LTVkYTUtNDA5MS05NmU3LTFiOGIyYmNlODRmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwMzAyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWU4ODExOTViM2NkNTRmNTg4OTQ4YWJlZTMyZjRmMmEyOGViN2ViM2NkNmUxZTdjNDUxYTMwNzQzYzQ0N2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QbbN4RqlmeFw3iY6slJmxXMxere5Se9RPhcsGbisNT4)
> 
> 我照做 然後把所有可能的方式都放在裡面還是一樣 下載後檔案名稱不變的也放進去 改變成cookie.txt也是

檔名維持原有的www.linetv.tw_cookies.txt 改檔名就讀取不到了
