### ISSUE TITLE
下載"friday影音"的字幕時發生問題

### ISSUE THREAD

**Issue by CoCoLaL** [wayneclub/Subtitle-Downloader#90]
您好:

#
我在下載"friday影音"時碰到如圖的狀況
![註解 2024-05-24 041039](https://github.com/wayneclub/Subtitle-Downloader/assets/109889564/61b051ba-81f7-413b-a800-e8987ef6b7e7)

下載的連結如下
https://video.friday.tw/anime/detail/1579

使用的平台是win10
IP是台灣, 未使用VPN
有加入Cookies

下載KKTV和LINE TV時都一切正常
唯獨"friday影音"發生了此情況

麻煩您了
謝謝!

**Comment by CoCoLaL** [comment]
您好
我有重新下載最新版的，然後登出所有friday上的裝置，再重新登入下載cookies
但還是出現一樣的警示

**Comment by CoCoLaL** [comment]
您好
我目前改用Python 3.10的版本後，就可以正常使用了!

**Comment by nanachisol** [comment]
最新的Python 3.13.2或者3.14 alpha 运行时会报错，错误信息与主楼类似。换用python-3.12.3 正常运行。
另外还需要先通过Microsoft C++ Build Tools安装Windows 11 SDK和C++ x64/x86 build tools才能执行install_requirements.bat。要不然会编译不通过。
