### ISSUE TITLE
Traceback (most recent call last)?     service['class'](args).main()?

### ISSUE THREAD

**Issue by KAK232** [wayneclub/Subtitle-Downloader#91]
![لقطة شاشة 2024-06-12 000525](https://github.com/wayneclub/Subtitle-Downloader/assets/169140265/7ddd7159-09c5-4aed-a213-e962ca85a769)
Traceback (most recent call last)

  service['class'](args).main()

**Comment by wayneclub** [comment]
> ![لقطة شاشة 2024-06-12 000525](https://private-user-images.githubusercontent.com/169140265/338746258-7ddd7159-09c5-4aed-a213-e962ca85a769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzM4NTIsIm5iZiI6MTcyMTczMzU1MiwicGF0aCI6Ii8xNjkxNDAyNjUvMzM4NzQ2MjU4LTdkZGQ3MTU5LTA5YzUtNGFlZC1hMjEzLWU5NjJjYTg1YTc2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMTE5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzNiZTU4NjYyMjU5ZjQ5YjM2NGFmODc1NDU1NDY3ODM2ZWJlMjYyMWJlODQ2ZmIyZGJlNTAwOTQ2OGQxZjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nD9bD0WgfnvKzjM7gJ0RiJdnXDBu29I1ewqUVSg1M7o) Traceback (most recent call last)
> 
> service['class'](args).main()

Update Viki, Please download and retry
