### ISSUE TITLE
Invaild dash_url, wrong vf! for IQ.com

### ISSUE THREAD

**Issue by Rule1311** [wayneclub/Subtitle-Downloader#92]
I am getting the below message whenever i try to download from iq.com
I renew my cookies multiple times but still no change.
Thank you.

url: https://www.iq.com/play/venus-in-the-sky-episode-1-24ivbgu8rqk?lang=en_us

Venus in the Sky

Season 1 total: 10 episode(s)   download all episodes
---------------------------------------------------------------
Finding Venus.in.the.Sky.S01E01.WEB-DL.iQIYI.vtt ...
Finding Venus.in.the.Sky.S01E01.WEB-DL.iQIYI.vtt ...
Invaild dash_url, wrong vf!
Renew your cookies and try again!
Press any key to continue . . .

**Comment by danny740211** [comment]
你的錯誤沒加入cookies ,此影片是vip的

**Comment by Rule1311** [comment]
I have a VIP account and I add the cookies.

**Comment by wayneclub** [comment]
> https://www.iq.com/play/venus-in-the-sky-episode-1-24ivbgu8rqk?lang=en_us

Fix iq.com, remove preview and behind the scenes.

**Comment by Rule1311** [comment]
Thank you for the fix.
