### ISSUE TITLE
KKTV 日劇單集無法下載字幕

### ISSUE THREAD

**Issue by hsiehtsunglung** [wayneclub/Subtitle-Downloader#97]
![螢幕擷取畫面 2024-07-21 192022](https://github.com/user-attachments/assets/b566e257-abcc-4c8d-bf11-1fbc096da719)

感謝製作好用程式，已奉上咖啡。
KKTV日劇雙字幕多集正常，單集無法下載。
單集是指特別篇那種只有一集。

**Comment by wayneclub** [comment]
> ![螢幕擷取畫面 2024-07-21 192022](https://private-user-images.githubusercontent.com/75589719/350764563-b566e257-abcc-4c8d-bf11-1fbc096da719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjMxMTEsIm5iZiI6MTcyMTYyMjgxMSwicGF0aCI6Ii83NTU4OTcxOS8zNTA3NjQ1NjMtYjU2NmUyNTctYWJjYy00YzhkLWJmMTEtMWZiYzA5NmRhNzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA0MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZTU3OGU4OGE4M2U2ZTFmMWY3NzZjYWQ2YTk3OWM2NjFlYTU2MDVmNWI3ODFiNjI2ZGI4N2RjYTEwN2M0ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MwrlnpQaz0JSidLbkBs5W0pcCOlC_DYQKJ30qF4RHIg)
> 
> 感謝製作好用程式，已奉上咖啡。 KKTV日劇雙字幕多集正常，單集無法下載。 單集是指特別篇那種只有一集。

感謝贊助，KKTV官網可能有修正，我再查看一下，並盡快修正

**Comment by wayneclub** [comment]
> ![螢幕擷取畫面 2024-07-21 192022](https://private-user-images.githubusercontent.com/75589719/350764563-b566e257-abcc-4c8d-bf11-1fbc096da719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjUyMDcsIm5iZiI6MTcyMTcyNDkwNywicGF0aCI6Ii83NTU4OTcxOS8zNTA3NjQ1NjMtYjU2NmUyNTctYWJjYy00YzhkLWJmMTEtMWZiYzA5NmRhNzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA4NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNTM5Yjk0ZGRkNDNhNzQzNzlkZGE4OTg0M2E1YmEwN2JmOTc4MzljNDhhYWM0OWZkMDk2MDYyNTBiYTkxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.esoj_kVQrBKR17feN7R8ElPCHDDqyO39Zs8j7HnxEHU)
> 
> 感謝製作好用程式，已奉上咖啡。 KKTV日劇雙字幕多集正常，單集無法下載。 單集是指特別篇那種只有一集。

[繼母與女兒的藍調.完結篇2024.2024.KKTV.WEB-DL.zip](https://github.com/user-attachments/files/16346200/2024.2024.KKTV.WEB-DL.zip)

**Comment by hsiehtsunglung** [comment]
成功了嗎？跪求教學，感謝您！

**Comment by wayneclub** [comment]
> ![螢幕擷取畫面 2024-07-21 192022](https://private-user-images.githubusercontent.com/75589719/350764563-b566e257-abcc-4c8d-bf11-1fbc096da719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzM2MzksIm5iZiI6MTcyMTczMzMzOSwicGF0aCI6Ii83NTU4OTcxOS8zNTA3NjQ1NjMtYjU2NmUyNTctYWJjYy00YzhkLWJmMTEtMWZiYzA5NmRhNzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYmM5YjFmYzQ5ZmY3OTY4MDg3N2NmOTRhMjcwMjY5OGI3YTM2NTZkYWE1MDZkOWNmOTZkMDZlYjM2YWZmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Y23LWPJUXhlogBtf6ytUxmzaJl08nTpa6qaL3DvyTc)
> 
> 感謝製作好用程式，已奉上咖啡。 KKTV日劇雙字幕多集正常，單集無法下載。 單集是指特別篇那種只有一集。

已更新，再試試

**Comment by hsiehtsunglung** [comment]
感謝可以了！
不過出現一點點錯誤訊息，回報一下。
再次奉上咖啡。

![螢幕擷取畫面 2024-07-23 202015](https://github.com/user-attachments/assets/e5f18508-5e4d-4fe3-9637-849801d77325)
![螢幕擷取畫面 2024-07-23 202042](https://github.com/user-attachments/assets/e9faa969-fb22-40fe-889f-ab406dbd4934)
